config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'photography' => 'pages#photography'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def photography
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> 
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Me", about_path %></li>
        <li><%= link_to "Photography", photography_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1><FONT COLOR="F0FFFF">About me</FONT></h1>
<hr class="featurette-divider">
<img src="https://pbs.twimg.com/profile_images/555212787987652608/0vu-z1yH.png" height = "200" width = "200"
align="left">
<p><FONT COLOR="F0FFFF">&nbsp;&nbsp;My name is Tarush Sinha. I am currently pursuing a Bachelors in Computer Science and working towards a double major in Business at the &nbsp;&nbsp;University of Maryland, College Park, MD.<br><br>&nbsp;&nbsp;I have a strong international background; having lived in Southeast Asia and the United States. I have demonstrated leadership skills and have &nbsp;&nbsp;excellent communication skills. I am trilingual in English, Mandarin, and Hindi & have proven my ability to work in a multi-cultural environment.<br><br>&nbsp;&nbsp;I am currently building this site as part of the OneMonth Rails course to learn Ruby on Rails. My other coding background is in Java, MySQL, &nbsp;&nbsp;Javascript, and HTML.
	<br>&nbsp;&nbsp;<FONT COLOR="F0FFFF">Need to get in touch?
	Contact me at:
	<button type="button" class="btn btn-success btn-sm">tarush[@]terpmail.umd.edu</button>
	or via
	</FONT><%= link_to "LinkedIn", "https://www.linkedin.com/pub/tarush-sinha/71/758/807", class: "btn btn-success btn-sm" %></p>



<!--This is Under Construction Message-->
<!--<div class= "alert alert-danger" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<strong>Sorry!</strong> This page is currently under construction
</div>
<br>
<br>
<p><%= link_to "Return to Home Page", root_path %></p>-->

app/views/pages/home.html.erb
<div class="jumbotron center">
	<div class="container">
	  <h1>Welcome to Pinteresting!</h1>
		<p>
			<%= link_to "Log in", "#", class: "btn btn-default btn-lg" %>
			<%= link_to "Sign up", "#", class: "btn btn-primary btn-lg" %>
		</p>
  </div>
</div>

<div class= "alert alert-danger" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<strong>Sorry!</strong> This page is currently still under construction
</div>

app/views/pages/photography.html.erb
<div id="carousel-example-generic" class="carousel slide container" style="height: 580px; width: 900px; margin: 0 auto" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active" data-interval="100"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1" class="carousel slide" data-interval="400"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2" class="carousel slide" data-interval="400"></li>
  </ol>
 
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="https://scontent-a-sjc.xx.fbcdn.net/hphotos-ash2/v/t1.0-9/524673_10151344306833798_1068282099_n.jpg?oh=47627858afa7b74bfdd23a47aa7d2c79&oe=55344D50" alt="...">
    </div>
    <div class="item">
      <img src="https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xfa1/t31.0-8/1415038_10152799407668798_2251493214651735421_o.jpg" alt="...">
    </div>
    <div class="item">
      <img src="https://scontent-a-sjc.xx.fbcdn.net/hphotos-xpa1/t31.0-8/1913468_10152269328418798_633938166_o.jpg" alt="...">
    </div>
  </div>
 
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
  </a>
</div> <!-- Carousel -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>

<hr class="featurette-divider">
<img src="https://scontent-a-sjc.xx.fbcdn.net/hphotos-xfa1/t31.0-8/1965538_10152269328463798_2068535706_o.jpg" height = "359" width = "540">
&nbsp;
<img src="https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xpa1/t31.0-8/1537669_10152269328443798_868951777_o.jpg" height = "359" width = "550">
<br><br>
&nbsp;&nbsp;<img src="https://scontent-b-sjc.xx.fbcdn.net/hphotos-xfp1/t31.0-8/1781652_10152714542143798_8976052217984081329_o.jpg" height = "358.5" width = "525.5">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://scontent-a-sjc.xx.fbcdn.net/hphotos-xfp1/t31.0-8/740051_10152089221253798_652448373_o.jpg" height = "359" width = "538.5">
<br><br>
<img src="https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-xap1/t31.0-8/1534738_10152089220318798_2089608056_o.jpg" height = "359" width = "538.5">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://scontent-a-sjc.xx.fbcdn.net/hphotos-xfp1/t31.0-8/1009040_10152153609468798_45555228_o.jpg" height = "359" width = "540">
<hr class="featurette-divider">
<center><%= link_to "Click here to view more of my photos", "https://www.flickr.com/photos/93022604@N05/", class: "btn btn-success btn-lg" %></center>
<br><br>